STORAGE_DATASOURCE: mg
#STORAGE_DATASINK: stdout
STORAGE_DATASINK: mg
MG_HOST: 172.17.18.83
MG_PORT: 27017
MG_USER: dbadmin
MG_PASSWORD: password123
MG_INPUT_DB: anomalydb
MG_CA_CERT: "/home/nadzya/Apps/log-aggregator/configs/LAD_CA.crt"
MG_VERIFY_CERT: true
MG_TARGET_DB: anomalydb
MG_INPUT_COLS:
  - utm_anomaly
  - network_anomaly
  - web_anomaly
MG_TARGET_COLS:
  - utm_aggregated
  - network_aggregated
  - web_aggregated
DATETIME_INDEX: timestamp
HOSTNAME_INDEX: hostname
AGGR_TIME_SPAN: 1296000
AGGR_EPS: 0.01
AGGR_MIN_SAMPLES: 2
