STORAGE_DATASOURCE: mg
#STORAGE_DATASINK: stdout
STORAGE_DATASINK: mg
MG_HOST: 172.17.18.83
MG_PORT: 27017
MG_USER: dbadmin
MG_PASSWORD: password123
MG_INPUT_DB: fluentdb
MG_CA_CERT: "/home/nadzya/Apps/log-aggregator/configs/LAD_CA.crt"
MG_VERIFY_CERT: true
MG_TARGET_DB: fluentdb
MG_INPUT_COLS:
  - web_logs
MG_TARGET_COLS:
  - web_anomaly_logs
DATETIME_INDEX: received_at
HOSTNAME_INDEX: hostname
MESSAGE_INDEX: message
AGGR_TIME_SPAN: 12960000
#AGGR_MAX_ENTRIES: 100
AGGR_EPS: 0.01
AGGR_MIN_SAMPLES: 2
